version: '4.40.0'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: lojavirtual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
